### ISSUE TITLE
colab t4

### ISSUE THREAD

**Issue by werruww** [ubergarm/vLLM-inference-AQLM#1]
import os
import torch
from vllm import LLM, SamplingParams
from torch.cuda.amp import autocast

# تعيين مسار للتخزين المؤقت على القرص
DISK_CACHE_DIR = "/content/model_cache"
os.makedirs(DISK_CACHE_DIR, exist_ok=True)

# تعيين متغيرات البيئة
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:64,expandable_segments:True'
os.environ['TRANSFORMERS_CACHE'] = DISK_CACHE_DIR
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
os.environ['HF_HOME'] = DISK_CACHE_DIR

# إنشاء ملف swap أصغر (4GB) لتقليل الضغط على الذاكرة
def setup_disk_cache():
    !fallocate -l 5G /content/swapfile
    !chmod 600 /content/swapfile
    !mkswap /content/swapfile
    !swapon /content/swapfile
    print("Swap file created and activated")

# تنظيف ذاكرة CUDA
def cleanup_cuda_memory():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    if torch.cuda.is_available():
        print(f"CUDA memory allocated: {torch.cuda.memory_allocated() / 1024**2:.2f} MB")

# إعداد التخزين المؤقت على القرص
setup_disk_cache()
cleanup_cuda_memory()

# إعداد النموذج مع مساحة تبديل أصغر
llm = LLM(
    model="ISTA-DASLab/Meta-Llama-3-70B-Instruct-AQLM-2Bit-1x16",
    trust_remote_code=True,
    tensor_parallel_size=1,
    gpu_memory_utilization=0.9,
    max_model_len=32,
    swap_space=5,  # تقليل مساحة التبديل إلى 4GB
    max_num_batched_tokens=32,  # تقليل عدد الرموز المدخلة
    max_num_seqs=1,
    enable_chunked_prefill=True,
    enforce_eager=True,
    dtype='float16'  # استخدام دقة منخفضة (نصف عائمة) لتقليل استهلاك الذاكرة
)

tokenizer = llm.get_tokenizer()

conversations = tokenizer.apply_chat_template(
    [{'role': 'user', 'content': 'Hi'}],
    tokenize=False,
)

# استخدام autocast لتقليل استخدام الذاكرة
with autocast():
    with torch.no_grad():
        outputs = llm.generate(
            [conversations],
            SamplingParams(
                temperature=0.7,
                top_p=0.9,
                max_tokens=16,
                presence_penalty=0.0,
                frequency_penalty=0.0,
                top_k=20,
            ),
            use_tqdm=False
        )

print(outputs[0].outputs[0].text)

# تنظيف الذاكرة بعد الانتهاء
cleanup_cuda_memory()
del llm
torch.cuda.empty_cache()

# إلغاء تفعيل swap في النهاية
!swapoff /content/swapfile
!rm /content/swapfile

mkswap: /content/swapfile: warning: wiping old swap signature.
Setting up swapspace version 1, size = 25 GiB (26843541504 bytes)
no label, UUID=34808180-1508-45e8-b0c8-aea3aa3c0be1
swapon: /content/swapfile: swapon failed: Invalid argument
Swap file created and activated
CUDA memory allocated: 0.00 MB
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
INFO 12-19 03:29:49 config.py:478] This model supports multiple tasks: {'score', 'reward', 'embed', 'generate', 'classify'}. Defaulting to 'generate'.
WARNING 12-19 03:29:51 config.py:556] aqlm quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 12-19 03:29:51 config.py:1364] Chunked prefill is enabled with max_num_batched_tokens=32.
WARNING 12-19 03:29:51 cuda.py:98] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
WARNING 12-19 03:29:51 config.py:604] Async output processing is not supported on the current platform type cuda.
INFO 12-19 03:29:51 llm_engine.py:249] Initializing an LLM engine (v0.6.5) with config: model='ISTA-DASLab/Meta-Llama-3-70B-Instruct-AQLM-2Bit-1x16', speculative_config=None, tokenizer='ISTA-DASLab/Meta-Llama-3-70B-Instruct-AQLM-2Bit-1x16', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=aqlm, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=ISTA-DASLab/Meta-Llama-3-70B-Instruct-AQLM-2Bit-1x16, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=True, use_async_output_proc=False, mm_cache_preprocessor=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"candidate_compile_sizes":[],"compile_sizes":[],"capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
INFO 12-19 03:29:52 selector.py:217] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 12-19 03:29:52 selector.py:129] Using XFormers backend.
INFO 12-19 03:29:53 model_runner.py:1092] Starting to load model ISTA-DASLab/Meta-Llama-3-70B-Instruct-AQLM-2Bit-1x16...
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
[<ipython-input-1-42d49ebfe16c>](https://localhost:8080/#) in <cell line: 36>()
     34 
     35 # إعداد النموذج مع مساحة تبديل أصغر
---> 36 llm = LLM(
     37     model="ISTA-DASLab/Meta-Llama-3-70B-Instruct-AQLM-2Bit-1x16",
     38     trust_remote_code=True,

23 frames
[/usr/local/lib/python3.10/dist-packages/torch/utils/_device.py](https://localhost:8080/#) in __torch_function__(self, func, types, args, kwargs)
    104         if func in _device_constructors() and kwargs.get('device') is None:
    105             kwargs['device'] = self.device
--> 106         return func(*args, **kwargs)
    107 
    108 # NB: This is directly called from C++ in torch/csrc/Device.cpp

OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacity of 14.75 GiB of which 47.06 MiB is free. Process 238998 has 14.70 GiB memory in use. Of the allocated memory 14.58 GiB is allocated by PyTorch, and 7.29 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by werruww** [comment]
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"  # To  prevent long warnings:)

tokenizer = AutoTokenizer.from_pretrained("ISTA-DASLab/Meta-Llama-3-70B-AQLM-PV-1Bit-1x16")
model = AutoModelForCausalLM.from_pretrained("ISTA-DASLab/Meta-Llama-3-70B-AQLM-PV-1Bit-1x16", torch_dtype="auto", device_map="auto")

model.generation_config.cache_implementation = "static"

model.forward = torch.compile(model.forward, mode="reduce-overhead", fullgraph=True)
input_text = "The theory of special relativity states "
input_ids = tokenizer(input_text, return_tensors="pt").to(model.device.type)

outputs = model.generate(**input_ids)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True))






/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Loading checkpoint shards: 100%
 3/3 [01:09<00:00, 22.91s/it]
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The 'batch_size' attribute of StaticCache is deprecated and will be removed in v4.49. Use the more precisely named 'self.max_batch_size' attribute instead.
Using `torch.compile`.
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:20: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:33: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:48: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant_transposed")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:62: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:75: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:88: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant_transposed")
---------------------------------------------------------------------------
Unsupported                               Traceback (most recent call last)
[<ipython-input-1-1d93fb47c769>](https://localhost:8080/#) in <cell line: 15>()
     13 input_ids = tokenizer(input_text, return_tensors="pt").to(model.device.type)
     14 
---> 15 outputs = model.generate(**input_ids)
     16 print(tokenizer.batch_decode(outputs, skip_special_tokens=True))

87 frames
[/usr/local/lib/python3.10/dist-packages/torch/_dynamo/exc.py](https://localhost:8080/#) in unimplemented(msg, from_exc, case_name)
    295     if from_exc is not _NOTHING:
    296         raise Unsupported(msg, case_name=case_name) from from_exc
--> 297     raise Unsupported(msg, case_name=case_name)
    298 
    299 

Unsupported: missing: LOAD_BUILD_CLASS

from user code:
   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 1163, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 913, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 640, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py", line 522, in forward
    query_states = self.q_proj(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/aqlm/inference.py", line 70, in forward
    self.prepare_matmul_op(input)
  File "/usr/local/lib/python3.10/dist-packages/aqlm/inference.py", line 85, in prepare_matmul_op
    self.gemv_op = _get_autograd_matmul_op(
  File "/usr/local/lib/python3.10/dist-packages/aqlm/inference.py", line 99, in _get_autograd_matmul_op
    class _QuantizedMatmul(torch.autograd.Function):

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

**Comment by werruww** [comment]
Can I have a complete deduction code in Colab T4
ISTA-DASLab/Meta-Llama-3-70B-AQLM-PV-1Bit-1x16

**Comment by werruww** [comment]
from transformers import AutoTokenizer, AutoModelForCausalLM

quantized_model = AutoModelForCausalLM.from_pretrained(
"ISTA-DASLab/Meta-Llama-3-70B-AQLM-PV-1Bit-1x16",
torch_dtype="auto", device_map="auto", low_cpu_mem_usage=True,
)
tokenizer = AutoTokenizer.from_pretrained("ISTA-DASLab/Meta-Llama-3-70B-AQLM-PV-1Bit-1x16")


output = quantized_model.generate(tokenizer("The inventor of the electric lamp is", return_tensors="pt")["input_ids"].cuda(), min_new_tokens=128, max_new_tokens=128)
print(tokenizer.decode(output[0]))




The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:20: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:33: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:48: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant_transposed")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:62: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:75: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:88: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant_transposed")
The inventor of the electric lamp isEMPLARY металли металли металли металли металлиückückückückückückückückückückückückückückückück

**Comment by werruww** [comment]
What is the solution to the incomprehensible words in the response form?

**Comment by werruww** [comment]
from transformers import AutoTokenizer, AutoModelForCausalLM

quantized_model = AutoModelForCausalLM.from_pretrained(
"ISTA-DASLab/Meta-Llama-3-70B-AQLM-PV-1Bit-1x16",
torch_dtype="auto", device_map="auto", low_cpu_mem_usage=True,
)
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-70B")




output = quantized_model.generate(tokenizer("What is the result 1+1=؟", return_tensors="pt")["input_ids"].cuda(), min_new_tokens=20, max_new_tokens=20)
print(tokenizer.decode(output[0]))




The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1965: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:20: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:33: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:48: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code1x16_matmat_dequant_transposed")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:62: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:75: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant")
/usr/local/lib/python3.10/dist-packages/aqlm/inference_kernels/cuda_kernel.py:88: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("aqlm::code2x8_matmat_dequant_transposed")
<|begin_of_text|>What is the result 1+1=؟vetica uncon uncon uncon uncon uncon uncon uncon uncon uncon uncon uncon uncon uncon

**Comment by werruww** [comment]
from transformers import AutoTokenizer, AutoModelForCausalLM

quantized_model = AutoModelForCausalLM.from_pretrained(
"ISTA-DASLab/Meta-Llama-3-70B-AQLM-PV-1Bit-1x16",
torch_dtype="auto", device_map="auto", low_cpu_mem_usage=True,
)
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-70B")

output = quantized_model.generate(tokenizer("1+1=؟", return_tensors="pt")["input_ids"].cuda(), min_new_tokens=20, max_new_tokens=20)
print(tokenizer.decode(output[0]))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's attention_mask to obtain reliable results.
Setting pad_token_id to eos_token_id:128001 for open-end generation.
<|begin_of_text|>1+1=؟586774774774774774774774774774774774774774774774774774774774


What is the solution for the incomprehensible model outputs even with changing the token?

**Comment by ubergarm** [comment]
This looks like bot spam?

If u are not a bot, go try aphrodite-engine instead! Cheers!
